### ISSUE TITLE
关于评论区默认头像无法加载的问题

### ISSUE THREAD

**Issue by alexinea** [picturepan2/thea#1]
Hi, @picturepan2 ，别来无恙。

我使用了你的Thea主题，发现我的站点不能显示评论者的默认头像（https://i2.wp.com/alexinea.com/wp-content/themes/thea/assets/img/avatar.png?ssl=1），而贵站是可以的。请问如何才能让wordpress缓存到我站的这张图呢~ 

靴靴~

**Comment by picturepan2** [comment]
@alexinea 你好，你有安装 Jetpack 插件？

**Comment by alexinea** [comment]
我找到原因了，您看一下 https://github.com/picturepan2/thea/blob/master/comments.php#L18 ，主题路径有些小问题。我现在改成了 https://github.com/alexinea/thea/blob/master/comments.php#L18 ，问题已解决。

谢谢 @picturepan2 的精彩模板：）

**Comment by picturepan2** [comment]
你把主题目录改名为 `thea-master` 了啊，那显然是需要修改了。

**Comment by alexinea** [comment]
😭

**Comment by picturepan2** [comment]
我看看较，能不能直接输出主题目录。
